### PR TITLE
added support for f5 exports that include a context

### PR DESCRIPTION
**Pull request by pwinckles**
**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-3522

# What does this Pull Request do?

Adds support for F5 exports that have a web context.

# How should this be tested?

1. Setup F5 on a tomcat instance where it's not deployed as the ROOT webapp.
2. Export the F5 objects
3. Run the upgrade util on the export

# Interested parties

@fcrepo4/committers

### CODE REVIEW

**Review by awoods — COMMENTED** [review]
This looks like it should work, but I am getting errors when upgrading from F5 -> F6... which might be related to fixes that @dbernstein has addressed in: https://github.com/fcrepo-exts/fcrepo-upgrade-utils/pull/24.

Once @dbernstein resolves the last comment in PR-24, and it is merged, and this PR-25 is rebased on top of it, I will test again... tomorrow evening or this weekend.

**Comment by pwinckles** [comment]
What are the errors?

**Comment by awoods** [comment]
```
INFO 19:04:29.773 (F5ToF6UpgradeManager) Starting upgrade: config=Config{sourceVersion=V_5, targetVersion=V_6, inputDir=../f5-upgrade, outputDir=../f6-upgrade, srcRdfLang=Lang:Turtle, baseUri='http://localhost:8080/fcrepo/rest', threads=8, digestAlgorithm='sha512', fedoraUser='fedoraAdmin', fedoraUserAddress='info:fedora/fedoraAdmin'}
INFO 19:04:29.804 (ResourceMigrator) Migrating info:fedora
INFO 19:04:30.143 (ResourceMigrator) Migrating info:fedora/ext
INFO 19:04:30.143 (ResourceMigrator) Migrating info:fedora/a
INFO 19:04:30.167 (ResourceMigrator) Migrating info:fedora/a/b
INFO 19:04:30.178 (ResourceMigrator) Failed to migration resource info:fedora/a/b. Rolling back...
ERROR 19:04:30.193 (MigrateResourceTask) Failed to process ResourceInfo{parentId='info:fedora/a', fullId='info:fedora/a/b', nameEncoded='b', outerDirectory=../f5-upgrade/fcrepo/rest/a, innerDirectory=../f5-upgrade/fcrepo/rest/a/b, type=CONTAINER}
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: ../f5-upgrade/fcrepo/rest/a/b
	at org.fcrepo.upgrade.utils.f6.ResourceMigrator.listDirectChildren(ResourceMigrator.java:362)
	at org.fcrepo.upgrade.utils.f6.ResourceMigrator.listAllChildren(ResourceMigrator.java:313)
	at org.fcrepo.upgrade.utils.f6.ResourceMigrator.migrateContainer(ResourceMigrator.java:168)
	at org.fcrepo.upgrade.utils.f6.ResourceMigrator.migrate(ResourceMigrator.java:124)
	at org.fcrepo.upgrade.utils.f6.MigrateResourceTask.run(MigrateResourceTask.java:59)
	at org.fcrepo.upgrade.utils.f6.MigrationTaskManager.lambda$submit$0(MigrationTaskManager.java:66)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.NoSuchFileException: ../f5-upgrade/fcrepo/rest/a/b
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
	at java.base/java.nio.file.Files.list(Files.java:3698)
	at org.fcrepo.upgrade.utils.f6.ResourceMigrator.listDirectChildren(ResourceMigrator.java:339)
	... 10 common frames omitted
INFO 19:04:30.207 (F5ToF6UpgradeManager) Upgrade complete.
```

**Comment by awoods** [comment]
`../f5-upgrade/fcrepo/rest/a/b` does not exist... but `../f5-upgrade/fcrepo/rest/a/b.ttl` does.

**Comment by pwinckles** [comment]
You're right that that should be fixed by the PR you referenced. But, what kind of resource are you expecting `info:fedora/a/b` to be?

**Comment by awoods** [comment]
See: https://gist.github.com/awoods/59eccb055821582176dfb10c5d0be027

**Comment by pwinckles** [comment]
@awoods Doesn't it seem like there's something wrong with your export? Does your export contain `a/b/c` and `a/b/c/binary`?

**Review by awoods — APPROVED** [review]

**Pull request merged**
